### ISSUE TITLE
Releases cannot be triggered via CI

### ISSUE THREAD

**Issue by Inkdpixels** [ImmoweltGroup/create-any-cli#100]
Most probably due to an outdated version of semantic-release, force an update and use the release/ublish config found in [create-config](https://github.com/ImmoweltGroup/create-config/blob/master/package.json)

**Comment by Inkdpixels** [comment]
@Romischart @kevroadrunner Oi guys, just pushed some changes to be able to release again this package, but unfortunately I cannot generate a `NPM_TOKEN` that is allowed to publish the package, could one of you guys do this and set it in the CI [settings of TravisCI](https://travis-ci.org/ImmoweltGroup/create-any-cli/settings) as well as re-trigger the build afterwards? Thanks :)

**Comment by kevroadrunner** [comment]
Sure mate, this should be fixed now. :-)
(https://travis-ci.org/ImmoweltGroup/create-any-cli/builds/423054515)
